### ISSUE TITLE
Implement a tracker list that keeps track of the found trackers by the user

### ISSUE THREAD

**Issue by Eftichios** [Eftichios/Level-4-Individual-Project#85]
This will be a list of all trackers we have information on. Initially they will be all greyed out, when the user finds a certain tracker they turn to green.

This will be under game metrics. We need to have a database entry for this list for each player that gets instantiated when the user creates their account. After a game is over, a service should be called that updates the player's list according to the trackers they found in game.

- [x] Database table for trackers - Implemented as a column in player's metrics
- [x] Modal view of this list of trackers
- [x] Instantiate player's trackers on account creation
- [ ] Extension passes tracker information to server (could be a request or sockets)
- [ ] Create a handler that updates tracker list after each game
